version: '3.8'

services:

  server:
    container_name: agent
    build:
      context: app
      dockerfile: Dockerfile
      args:
        REBUILD_TRIGGER: ${REQUIREMENTS_REBUILD_TRIGGER:-default}
    ports:
      - 5050:5050
    volumes:
      - ./app:/app
    env_file:
      - ./app/.prod.env
    depends_on:
      - redis
      - qdrant
    networks:
      - agent-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_storage:/data
    networks:
      - agent-network
    restart: unless-stopped

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - agent-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  redis_storage:
  qdrant_storage:

networks:
  agent-network:
    driver: bridge
